profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^update/$', views.ProfileUpdate.as_view(), name='profile_update'),
]

python_learning/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from products.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),

    path('', home, name='home'),
]

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name of the Product')
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    active = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='products', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'products'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
from django.urls import reverse


class UserProfile (models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name='user', related_name='profile',
                                on_delete=models.CASCADE)
    avatar_url = models.CharField(max_length=256, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.user.email)

    class Meta:
        db_table = 'user_profile'

    def get_absolute_url(self):
        return reverse('profiles:profile', kwargs={'pk': self.user.id})

profiles/forms.py
from django.forms import ModelForm
from .models import UserProfile, User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar_url', 'phone_number', 'bio', 'location', 'birth_date')

products/views.py
from django.shortcuts import render

from .models import Product
# Create your views here.


def home(request):

    products = Product.objects.all()

    return render(request, 'products/home.html', {'products': products})

profiles/views.py
from django.shortcuts import render
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from profiles.models import UserProfile, User
# Create your views here.


class ProfileView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = UserProfile
    template_name = 'profiles/profile_detail.html'
    raise_exception = True

    def test_func(self):
        return self.request.user.id == int(self.kwargs['pk'])


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = UserProfile
    fields = ['avatar_url', 'phone_number', 'bio', 'location', 'birth_date']
    template_name = 'profiles/profile_update.html'

    def get_object(self, queryset=None):
        return UserProfile.objects.get(user=self.request.user)

templates/_form.html
<div class="an-page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="content-body">
          <div class="an-section-container">
            <div class="an-listing-result-content full-width">
              <div class="an-tab-container">
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="all">
                    <div class="an-edit-profile">
                      {% if form.is_multipart %}
                        <form enctype="multipart/form-data" method="post" action="" class="an-form">
                      {% else %}
                        <form method="post" action="" class="an-form">
                      {% endif %}
                      <div class="row">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Update" class="an-btn btn-success" />
                      </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Elements</title>
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">


  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500%7COpen+Sans:400,600%7CCabin:400i" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/vendor-styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css'%}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div id="an-main-wrapper">
  <header class="an-header">
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-bullseye color-primary"></i>My portal</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% if request.user.is_authenticated %}
                <a class="sign-up-link" href="{% url 'profiles:profile' pk=user.id %}"><i class="fa fa-user"></i><span>Logout</span></a>
              {% else %}
                <a class="sign-up-link" href="{% url 'account_login' %}"><i class="fa fa-user"></i><span>Login/Signup</span></a>
              {% endif %}
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header> <!-- end an-header -->

  {% block content %}
  {% endblock %}

  <footer class="an-footer">
    <div class="container">
      <div class="an-footer-bottom">
        <div class="row">
          <div class="col-md-2 col-sm-6">
            <div class="an-widget">
              <h4 class="an-small-title light-color">Menu</h4>
              <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Category</a></li>
                <li><a href="#">Listing</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-2 col-sm-6">
            <div class="an-widget">
              <h4 class="an-small-title light-color">Support</h4>
              <ul>
                <li><a href="#">Prvecy Policy</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Terms &amp; Service</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div>
          </div>

          <div class="col-md-2 col-sm-6">
            <div class="an-widget">
              <h4 class="an-small-title light-color">Manage</h4>
              <ul>
                <li><a href="#">Account</a></li>
                <li><a href="#">Listing</a></li>
                <li><a href="#">Register</a></li>
                <li><a href="#">Subscription</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-2 col-sm-6">
            <div class="an-widget">
              <h4 class="an-small-title light-color">Quick Links</h4>
              <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Agency Profile</a></li>
                <li><a href="#">Activity</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3 col-md-push-1 col-sm-6">
            <div class="an-widget newsletter">
              <h4 class="an-small-title light-color">Subscribe to our news</h4>
              <p>Contrary to popular belief, Lorem Ipsum is not simply random text.
                It has roots in a piece of classical Latin.</p>
              <form action="#" class="an-form" method="post" id="subscribe">
                <input type="email" class="an-form-control dark" placeholder="E-mail" id="subscr_email" required>
                <button type="submit" class="an-btn an-btn-default btn-submit-full" id="subscr_btn"><i class="ion-ios-paperplane"></i></button>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div> <!-- end container -->
    <div class="an-footer-copyright">
      <div class="container">
        <div class="content">
          <p class="copyrights">© 2017 Catalog Directory by analoglife. All rights reserved</p>
          <ul class="an-social-icons">
            <li><a href="#"><i class="ion-social-twitter"></i></a></li>
            <li><a href="#"><i class="ion-social-facebook"></i></a></li>
            <li><a href="#"><i class="ion-social-pinterest"></i></a></li>
            <li><a href="#"><i class="ion-social-linkedin"></i></a></li>
          </ul>

        </div>
      </div>
    </div>
  </footer> <!-- end an-footer -->
  <div class="an-loader">
    <div class="fl spinner2">
      <div class="spinner-container container1">
        <div class="circle1"></div>
        <div class="circle2"></div>
        <div class="circle3"></div>
        <div class="circle4"></div>
      </div>
      <div class="spinner-container container2">
        <div class="circle1"></div>
        <div class="circle2"></div>
        <div class="circle3"></div>
        <div class="circle4"></div>
      </div>
      <div class="spinner-container container3">
        <div class="circle1"></div>
        <div class="circle2"></div>
        <div class="circle3"></div>
        <div class="circle4"></div>
      </div>
    </div>
  </div>
</div> <!-- end main wrapper -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/selectize.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
<script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
</body>
</html>

templates/products/home.html
{% extends "base.html" %}

{% block content %}
<!-- Begin page content -->
<main role="main" class="container">
  <h1>Products</h1>

  {% for category in categories %}
    <p>{{ category.name }}</p>
    {% for product in category.products %}
      <p>{{ product.name }}</p>
    {% endfor %}
  {% endfor %}

</main>

{% endblock %}

templates/profiles/profile_detail.html
{% extends "base.html" %}

{% block content %}

    <div class="an-inner-banner">
        <div class="container">
            <div class="an-agency-single an-agent-single">
                <div class="left">
                    <div class="image" style="background: url('{{ userprofile.avatar_url }}') center center no-repeat; background-size: cover;">
                        <a class="edit-btn" href="{% url 'profiles:profile_update' %}"><i class="ion-ios-gear"></i>Edit</a>
                    </div>
                    <div class="name">
                        <div class="an-title-container center">
                            <h1 class="an-title"><a href="#">{% if userprofile.user.get_full_name %}{{ userprofile.user.get_full_name }}
                            {% else %}{{ user.email }}{% endif %}</a></h1>
                        </div> <!-- end title container -->
                    </div>

                    <div class="listing-meta">
                        <span><i class="ion-android-call"></i>{{ userprofile.phone_number }}</span>
                        <span><i class="typcn typcn-location"></i>{{ userprofile.location }}</span>
                        <span><i class="ion-android-mail"></i>{{ userprofile.user.email }}</span>
                    </div>
                    <div class="listing-count">
                        <a class="an-btn an-btn-default icon-right" href="#">Follow <i class="ion-person-add"></i></a>
                        <a class="an-btn an-btn-default icon-right" href="#">Send message <i class="ion-paper-airplane"></i></a>
                        <a class="an-btn an-btn-default icon-right" href="{% url 'account_logout' %}">Logout <i class="fa fa-user"></i></a>
                    </div>
                </div>
            </div>

        </div> <!-- end cotnainer -->
    </div>

{% endblock %}

templates/profiles/profile_update.html
{% extends "base.html" %}

{% block content %}
{% include '_form.html' %}

{% endblock %}